### ISSUE TITLE
[JVM only] server hangs indefinitely until stdin input

### ISSUE THREAD

**Issue by kubukoz** [neandertech/langoustine#157]
`LangoustineApp`-created server processes appear not to when they get a SIGTERM.

Reproduction:

1.
```scala
//> using scala "3.3.0-RC4"
//> using lib "tech.neander::langoustine-app::0.0.19"
import cats.effect.IO
import cats.implicits._
import jsonrpclib.fs2.given
import langoustine.lsp.LSPBuilder
import langoustine.lsp.app.LangoustineApp
import fs2.io.file.Files
import fs2.io.file.Path

object Main extends LangoustineApp.Simple {

  val writePid =
    Files[IO]
      .writeAll(Path("PID"))
      .apply(fs2.Stream(ProcessHandle.current().pid().toString).through(fs2.text.utf8.encode[IO]))
      .compile
      .drain

  override def server: IO[LSPBuilder[cats.effect.IO]] = writePid *> LSPBuilder.create[IO].pure[IO]

}
```

2. `scala-cli --power package . -f -o server`
3. `./server`
4. in another tab, `kill $(cat PID)`
5. The server is still running, and needs a newline in stdin or a ctrl+C to shut down

**Comment by kubukoz** [comment]
My wild guess is that this is actually an fs2 issue - here's stdin:

`Sync[F].blocking(System.in)`

**Comment by kubukoz** [comment]
ha! it does work, it's just that 0.0.19 of Langoustine is still calling the old `stdin` because it wasn't recompiled against the new one.

@keynmol, would you mind releasing a 0.0.20 from the latest main? using s01 snapshots just ain't that convenient

**Comment by keynmol** [comment]
0.0.20 is being released as we speak, and I confirmed with you repro that the latest snapshot does indeed terminate.
