### ISSUE TITLE
(feature request) Tracer: Linking request/response in interaction view

### ISSUE THREAD

**Issue by kubukoz** [neandertech/langoustine#36]
It would be amazing if one could see both the request & the response for a given request while viewing the interaction's client or server. For example:

<img width="1688" alt="image" src="https://user-images.githubusercontent.com/894884/187082810-8ae6f026-5d1a-4723-a647-f7bfb5f7f296.png">

<img width="1686" alt="image" src="https://user-images.githubusercontent.com/894884/187082820-08bcedda-b632-44d3-a637-02f303edcd45.png">

^ both of the JSON snippets could be shown whenever you open either the request or the response.

**Comment by kubukoz** [comment]
I guess the client/server spans should still show up on the shared timeline so that you could see the timings of each request/response. I'd still link them in the more detailed view (like the LHS on the above) for ease of use.

**Comment by keynmol** [comment]
I'm glad you're filling out backlog for me :D Yeah, it's the most annoying part of it - I think responses should be inline with the request buttons, not separate interactions in the timeline

**Comment by kubukoz** [comment]
I think we had a race condition so I'll just repeat:

> the client/server spans should still show up on the shared timeline so that you could see the timings of each request/response

This is a really nice feature to keep (e.g. on the screenshots above you can see that we had two `codeLens` requests and then two responses).
