### ISSUE TITLE
(help needed?) Tracer: Can't pass flags to underlying server when running via `cs launch`

### ISSUE THREAD

**Issue by kubukoz** [neandertech/langoustine#38]
This might be a me thing, but I'm not able to pass a flag to the underlying server (which is also a `cs launch` call):

```bash
cs launch tech.neander:langoustine-tracer_3:latest.release -- cs launch --ttl 0 com.kubukoz.playground:lsp_2.13:0.4.0
```

Is this something that could be fixed in the tracer, or could it be related to how `cs launch` passes parameters?

**Comment by keynmol** [comment]
I think you need two `--` because of how `cs launch` works

```
cs launch tech.neander:langoustine-tracer_3:latest.release -- cs launch com.kubukoz.pl
ayground:lsp_2.13:0.4.0 -- --ttl 0 
```

**Comment by keynmol** [comment]
I.e. `cs launch <jar coordinates> -- <app arguments>`

**Comment by kubukoz** [comment]
does that set the TTL for the outer coursier or the inner one though? 😅

**Comment by keynmol** [comment]
Oh wait, I see what you mean. `--ttl` is not your flag.

When I run your command I see

```
velvetbaldmime   97922   0.0  1.3 415262160 217216 s006  S+    4:59pm   0:04.54 /usr/bin/java -jar /Users/velvetbaldmime/.tools/cs launch --ttl 0 com.kubukoz.playground:lsp_2.13:0.4.0
```

Meaning tracer passed all the flags correctly to coursier

**Comment by kubukoz** [comment]
you mean the one from the original post? (found a newline in there, fixed now)

It gives me this:

```
Unexpected option: --ttl

Usage: tracer [--port <integer>] <lspCommand>...

Launch Langoustine Tracer

Options and flags:
    --help
        Display this help text.
    --port <integer>
        Port to start Tracer on
```

**Comment by kubukoz** [comment]
My guess is that `Opts.arguments` doesn't capture `--ttl` (as it's an option, not an argument) - Decline sees an extra option and complains

**Comment by kubukoz** [comment]
oh boy... I think I got it:

```bash
cs launch tech.neander:langoustine-tracer_3:latest.release -- -- cs launch com.kubukoz.playground:lsp_2.13:0.4.0 --ttl 0
```

The double `--` was a good idea, it's just that cs wants `--ttl` after `launch`.

**Comment by kubukoz** [comment]
A+ customer support, would complain again
