### ISSUE TITLE
Tracer: payload view doesn't scroll

### ISSUE THREAD

**Issue by kubukoz** [neandertech/langoustine#39]
It's not possible to scroll down on a large payload.

Browser: firefox on mac

Something feels sus about the height of the element:

<img width="2375" alt="image" src="https://user-images.githubusercontent.com/894884/187084944-01afd5a9-2b1b-448a-8023-8d5bea19363a.png">

**Comment by kubukoz** [comment]
Workaround: if you select text and go down, it scrolls.

**Comment by keynmol** [comment]
Yeah that's the issue I found with scrollables and sticky position of the center div.

I'm sure it's solvable with 
![](https://i.imgflip.com/6rflty.jpg)

**Comment by kubukoz** [comment]
On the good note, horizontal scroll is working!
