### ISSUE TITLE
Tracer: server-sent requests not showing?

### ISSUE THREAD

**Issue by kubukoz** [neandertech/langoustine#99]
I think server-sent requests (such as `workspace/configuration`) aren't showing up in the tracer.

For example, my formatter asks the client for some config, but it's not shown here:

<img width="1567" alt="image" src="https://user-images.githubusercontent.com/894884/202623380-c5866ef7-fdad-4538-b372-d6490b447e2b.png">

Also, I'm seeing some weird mismatches (e.g. a request showing up with another one's body), especially around non-standard requests... I'll try to report that separately sometime.

**Comment by keynmol** [comment]
It all sounds very plausible. 

How do I know that? Well, because I totally forgot that you can have requests going in the other direction.
